name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'

env:
  TF_VERSION: '1.0.0'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment }}
        TF_VAR_region: ${{ secrets.AWS_REGION }}
        TF_VAR_delegated_account_id: ${{ secrets.DELEGATED_ACCOUNT_ID }}
        TF_VAR_template_bucket_name: ${{ secrets.TEMPLATE_BUCKET_NAME }}
        TF_VAR_access_analyzer_template_file: ${{ secrets.ACCESS_ANALYZER_TEMPLATE_FILE }}
        TF_VAR_detective_template_file: ${{ secrets.DETECTIVE_TEMPLATE_FILE }}
        TF_VAR_guardduty_template_file: ${{ secrets.GUARDDUTY_TEMPLATE_FILE }}
        TF_VAR_inspector_template_file: ${{ secrets.INSPECTOR_TEMPLATE_FILE }}
        TF_VAR_security_hub_template_url: ${{ secrets.SECURITY_HUB_TEMPLATE_URL }}
        TF_VAR_config_template_url: ${{ secrets.CONFIG_TEMPLATE_URL }}
        TF_VAR_inspection_lambda_template_url: ${{ secrets.INSPECTION_LAMBDA_TEMPLATE_URL }}
        TF_VAR_macie_template_url: ${{ secrets.MACIE_TEMPLATE_URL }}
        TF_VAR_subdomain_delegation_template_file: ${{ secrets.SUBDOMAIN_DELEGATION_TEMPLATE_FILE }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
