name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
      delegated_account_id:
        description: 'Delegated AWS account ID'
        required: true
      template_bucket_name:
        description: 'S3 bucket name for templates'
        required: true

env:
  TF_VERSION: '1.0.0'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="environment=${{ github.event.inputs.environment }}" \
          -var="region=${{ github.event.inputs.region }}" \
          -var="delegated_account_id=${{ github.event.inputs.delegated_account_id }}" \
          -var="template_bucket_name=${{ github.event.inputs.template_bucket_name }}" \
          -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
