name: Deploy Terraform Stack

# Trigger the workflow manually
on:
  workflow_dispatch:
    inputs:
      enable_access_analyzer:
        description: 'Enable Access Analyzer Stack'
        required: true
        default: 'false'
        type: boolean
      enable_guardduty:
        description: 'Enable GuardDuty Stack'
        required: true
        default: 'false'
        type: boolean
      enable_security_hub:
        description: 'Enable Security Hub Stack'
        required: true
        default: 'false'
        type: boolean
      enable_inspector:
        description: 'Enable Inspector Stack'
        required: true
        default: 'false'
        type: boolean
      enable_detective:
        description: 'Enable detective Stack'
        required: true
        default: 'false'
        type: boolean
      enable_config:
        description: 'Enable Config Stack'
        required: true
        default: 'false'
        type: boolean
      enable_inspection_lambda:
        description: 'Enable Inspection Lambda Stack'
        required: true
        default: 'false'
        type: boolean
      enable_macie:
        description: 'Enable Macie Stack'
        required: true
        default: 'false'
        type: boolean
      confirm_apply:
        description: 'Confirm Apply'
        required: true
        default: 'false'
        type: boolean

jobs:
  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug input values (before initializing Terraform)
      - name: Debug Terraform Inputs
        run: |
          echo "Enable Access Analyzer: ${{ github.event.inputs.enable_access_analyzer }}"
          echo "Enable GuardDuty: ${{ github.event.inputs.enable_guardduty }}"
          echo "Enable Security Hub: ${{ github.event.inputs.enable_security_hub }}"
          echo "Enable Inspector: ${{ github.event.inputs.enable_inspector }}"
          echo "Enable Config: ${{ github.event.inputs.enable_config }}"
          echo "Enable Inspection Lambda: ${{ github.event.inputs.enable_inspection_lambda }}"
          echo "Enable Macie: ${{ github.event.inputs.enable_macie }}"
          echo "Enable Notification Webhook: ${{ github.event.inputs.enable_notification_webhook }}"
          echo "Region: ${{ secrets.AWS_REGION }}"

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  # Specify your desired version

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # Step 5: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 6: Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -out=tfplan \
            -var "enable_access_analyzer=${{ github.event.inputs.enable_access_analyzer }}" \
            -var "enable_guardduty=${{ github.event.inputs.enable_guardduty }}" \
            -var "enable_security_hub=${{ github.event.inputs.enable_security_hub }}" \
            -var "enable_inspector=${{ github.event.inputs.enable_inspector }}" \
            -var "enable_config=${{ github.event.inputs.enable_config }}" \
            -var "enable_inspection_lambda=${{ github.event.inputs.enable_inspection_lambda }}" \
            -var "enable_macie=${{ github.event.inputs.enable_macie }}" \
            -var "enable_notification_webhook=${{ github.event.inputs.enable_notification_webhook }}" \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "delegated_account_id=${{ secrets.DELEGATED_ACCOUNT_ID }}" \
            -var "template_bucket_name=${{ secrets.TEMPLATE_BUCKET_NAME }}" \
            -var "role_to_assume=${{ secrets.ROLE_TO_ASSUME }}" \
            -var "MacieMasterAccountId=${{ secrets.MASTER_ACCOUNT_ID }}" \
            -var "access_analyzer_template_file=${{ secrets.ACCESS_ANALYZER_TEMPLATE_FILE }}" \
            -var "detective_template_file=${{ secrets.DETECTIVE_TEMPLATE_FILE }}"

      # Step 7: Check Terraform Plan result
      - name: Check Plan Result
        run: |
          if terraform show -json | jq -e '.planned_values.root_module.resources | length > 0'; then
            echo "Plan successful! Resources will be created."
          else
            echo "Plan successful but no changes detected."
          fi

      # Step 8: Apply Terraform (manual approval required)
      - name: Apply Terraform (manual approval required)
        if: ${{ github.event.inputs.confirm_apply == 'true' }}  # Only apply if 'true'
        run: | 
          terraform apply -auto-approve tfplan

      # Step 9: Output Terraform results
      - name: Terraform Output
        run: terraform output

      # Step 10: Handle errors (Optional, for better debugging)
      - name: Handle errors
        if: failure()
        run: |
          echo "Terraform apply failed. Please check the logs for details."
